"""add performance indexes for dedup lookup and file/folder listing

Revision ID: ebe6152daddb
Revises: f544e6b7f7a5
Create Date: 2026-07-12 15:05:16.111321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe6152daddb'
down_revision: Union[str, Sequence[str], None] = 'f544e6b7f7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_file_versions_checksum_sha256'), 'file_versions', ['checksum_sha256'], unique=False)
    op.create_index('ix_files_owner_deleted_updated', 'files', ['owner_id', 'is_deleted', 'updated_at'], unique=False)
    op.create_index('ix_files_owner_folder_deleted', 'files', ['owner_id', 'folder_id', 'is_deleted'], unique=False)
    op.create_index('ix_folders_owner_parent_deleted', 'folders', ['owner_id', 'parent_id', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_folders_owner_parent_deleted', table_name='folders')
    op.drop_index('ix_files_owner_folder_deleted', table_name='files')
    op.drop_index('ix_files_owner_deleted_updated', table_name='files')
    op.drop_index(op.f('ix_file_versions_checksum_sha256'), table_name='file_versions')
    # ### end Alembic commands ###
