"""add account lockout fields to users

Revision ID: 382874af0d70
Revises: fa31f08f48c9
Create Date: 2026-07-11 06:30:12.654317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382874af0d70'
down_revision: Union[str, Sequence[str], None] = 'fa31f08f48c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # Drop the server_default after backfill - new rows get the value from
    # the ORM's `default=0` instead; we don't want a stale DB-level default
    # masking future application-level changes.
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('failed_login_attempts', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
