"""add chunk_size_bytes to file_versions

Revision ID: f544e6b7f7a5
Revises: 382874af0d70
Create Date: 2026-07-11 06:44:36.051937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f544e6b7f7a5'
down_revision: Union[str, Sequence[str], None] = '382874af0d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('file_versions', sa.Column('chunk_size_bytes', sa.BigInteger(), nullable=False, server_default='0'))
    with op.batch_alter_table('file_versions') as batch_op:
        batch_op.alter_column('chunk_size_bytes', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_versions', 'chunk_size_bytes')
    # ### end Alembic commands ###
