worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    # Allow large chunk bodies (individual chunks, not whole 10GB files)
    client_max_body_size 50m;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=20r/s;

    upstream cloudvault_backend {
        server backend:8000;
    }

    server {
        listen 80;
        server_name _;

        location /health {
            proxy_pass http://cloudvault_backend;
        }

        location /ws/ {
            proxy_pass http://cloudvault_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 3600s;
        }

        location / {
            limit_req zone=api_limit burst=40 nodelay;
            proxy_pass http://cloudvault_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
